config/routes.rb
Canvas::Application.routes.draw do

  resources :businessmodels do
    member do
      post 'user'
    end
  end

  resources :canvas_fields
  resources :postits
  resources :comments

  root :to => 'static_pages#home'

  match 'help', :to => 'static_pages#help'
  match 'about', :to => 'static_pages#about'

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

end

app/models/businessmodel.rb
# == Schema Information
#
# Table name: businessmodels
#
#  id         :integer          not null, primary key
#  token      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Businessmodel < ActiveRecord::Base

  #validates :token,  presence: true, length: { maximum: 50 }

  has_many :canvas_fields
  has_many :comments, as: :commentable
  #after_create :generate_token

  protected

  def generate_token
    random_token = SecureRandom.urlsafe_base64(nil, false)
    self.update_attribute(:token, random_token)
  end
end

app/models/canvas_field.rb
# == Schema Information
#
# Table name: canvas_fields
#
#  id               :integer          not null, primary key
#  businessmodel_id :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  title            :string(255)
#

class CanvasField < ActiveRecord::Base
  attr_accessible :businessmodel_id, :title

  belongs_to :businessmodel
  has_many :postits
  has_many :comments, as: :commentable

  validates :title, presence: true, length: { maximum: 50 }
  validates :businessmodel_id, presence: true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  comment          :string(255)
#  commentable_id   :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  commentable_type :string(255)
#  username         :string(255)
#

class Comment < ActiveRecord::Base
  attr_accessible :comment, :commentable_id, :commentable_type, :username
  belongs_to :commentable, polymorphic: true
  default_scope { order('created_at DESC') }
end

app/models/postit.rb
# == Schema Information
#
# Table name: postits
#
#  id              :integer          not null, primary key
#  title           :string(255)
#  content         :text
#  canvas_field_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  link            :string(255)
#

class Postit < ActiveRecord::Base
  attr_accessible :canvas_field_id, :content, :title, :link

  belongs_to :canvas_field
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_model?

  def current_model?
    session[:model_id].present?
  end

  def load_model
    @businessmodel = Businessmodel.find(session[:model_id]) if current_model?
  end

  def load_username
    if cookies[:username]
      @username = cookies[:username]
    else
      @username = "unnamed"
    end
  end
end

app/controllers/businessmodels_controller.rb
class BusinessmodelsController < ApplicationController

  before_filter :load_username, :only => [:show]

  def new
    @businessmodel = Businessmodel.create
    @businessmodel.save
    @businessmodel.canvas_fields.create(:title => "Key Partners")
    @businessmodel.canvas_fields.create(:title => "Key Activities")
    @businessmodel.canvas_fields.create(:title => "Key Resources")
    @businessmodel.canvas_fields.create(:title => "Value Propositions")
    @businessmodel.canvas_fields.create(:title => "Customer Relationships")
    @businessmodel.canvas_fields.create(:title => "Channels")
    @businessmodel.canvas_fields.create(:title => "Customer Segments")
    @businessmodel.canvas_fields.create(:title => "Cost Structure")
    @businessmodel.canvas_fields.create(:title => "Revenue Streams")
    session[:model_id] = @businessmodel.id
    redirect_to @businessmodel
  end

  def show
    @businessmodel = Businessmodel.find(params[:id])
    @keypartners       = @businessmodel.canvas_fields.find_by_title("Key Partners")
    @keyactivities     = @businessmodel.canvas_fields.find_by_title("Key Activities")
    @keyresources      = @businessmodel.canvas_fields.find_by_title("Key Resources")
    @valuepropositions = @businessmodel.canvas_fields.find_by_title("Value Propositions")
    @customerrelations = @businessmodel.canvas_fields.find_by_title("Customer Relationships")
    @channels          = @businessmodel.canvas_fields.find_by_title("Channels")
    @customersegments  = @businessmodel.canvas_fields.find_by_title("Customer Segments")
    @coststructure     = @businessmodel.canvas_fields.find_by_title("Cost Structure")
    @revenuestreams    = @businessmodel.canvas_fields.find_by_title("Revenue Streams")
    session[:model_id] = @businessmodel.id

    @comment = Comment.new
    @type = @businessmodel.class
    @cid = @businessmodel.id
    @comments = @businessmodel.comments
    @postit = Postit.new
  end

  def user
    cookies[:username] = params[:businessmodel][:username]
    redirect_to :back
  end

end

app/controllers/canvas_fields_controller.rb
class CanvasFieldsController < ApplicationController

  before_filter :load_model, :only => [:create, :destroy, :show, :update, :edit]
  before_filter :load_field, :only => [:destroy, :show, :update, :edit]
  before_filter :load_username, :only => [:show]

  def show
    @comment = Comment.new
    @type = @canvasfield.class
    @cid = @canvasfield.id
    @comments = @canvasfield.comments

    @postit = Postit.new
  end

  private

    def load_field
      @canvasfield = CanvasField.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :load_model, :only => [:create, :index]
  before_filter :load_comment, :only => [:destroy, :show, :update, :edit]
  before_filter :load_username, :only => [:new]

  def create
    if current_model?
      @comment = Comment.new(params[:comment])
      @comment.save
      redirect_to :back
    else
      redirect_to root_path
    end
  end

  def index
    unless params[:fieldid]
      @comments = @businessmodel.comments
    else
      @field = CanvasField.find(params[:fieldid])
      @comments = @field.comments
    end

  end

  private

    def load_comment
      @comment = Comment.find(params[:id])
    end
end

app/controllers/postits_controller.rb
class PostitsController < ApplicationController

  before_filter :load_model, :only => [:create, :destroy, :show, :update, :edit]
  before_filter :load_postit, :only => [:destroy, :show, :update, :edit]

  def new
    session[:return_to] = request.referer
    @postit = Postit.new
    @canvasfield = CanvasField.find(params[:field])
  end

  def create
    if current_model?
      @postit = Postit.new(params[:postit])
      @postit.save
      redirect_to :back#session[:return_to]
    else
      redirect_to root_path
    end
  end

  def edit
    session[:return_to] = request.referer
    @postit = Postit.find(params[:id])
  end

  def update
    if @postit.update_attributes(params[:postit])
      redirect_to :back#session[:return_to]
    else
      redirect_to root_path
    end
  end

  private

    def load_postit
      @postit = Postit.find(params[:id])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_filter :load_model

  def home
  end

  def help
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Canvas Collaborator"
    if (page_title.nil? or page_title.empty?)
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def current_user?(user)
    user == current_user
  end

  def debug_enabled?
    Rails.env.development?
  end

  def nav_tab(title, url, options = {})
    current_tab = options.delete(:current)
    options[:class] = (current_tab == title) ? 'active' : 'inactive'
    content_tag(:li, link_to(title, url), options)
  end

  def currently_at(tab)
    render partial: 'layouts/nav', locals: {current_tab: tab}
  end

end

app/views/businessmodels/_canvasfield.haml
.panel.panel-default
  .panel-heading.fieldtitle
    %b= link_to field.title, field
    %br
    .badge
      - if field.comments.count > 0
        = link_to field.comments.count.to_s + ' comments', '#comments_' + field.title.delete(' '), data: { toggle: "modal" }
      - else
        no comments

= render field.postits
.pull-right
  = link_to "+", '#new_postit' + field.id.to_s, data: { toggle: "modal" }, :class => "badge"


= render :partial => 'comments/index', :locals => { :comments => field.comments, :tagit => field.title.delete(' ')}
= render :partial => 'postits/new',  :locals => { :fieldid => field.id }

app/views/businessmodels/show.haml
- provide(:title, 'Businessmodel')
- currently_at 'Businessmodel'

.row.top
  .col-md-9
    .row
      .col-md-2.nopadding
        .f2
          = render :partial => 'canvasfield', :locals => { :field => @keypartners }
      .col-md-3.nopadding
        .row
          .col-xs-12
            .f
              = render :partial => 'canvasfield', :locals => { :field => @keyactivities }
        .row
          .col-xs-12
            .f
              = render :partial => 'canvasfield', :locals => { :field => @keyresources }
      .col-md-2.nopadding
        .f2
          = render :partial => 'canvasfield', :locals => { :field => @valuepropositions }
      .col-md-3.nopadding
        .row
          .col-xs-12
            .f
              = render :partial => 'canvasfield', :locals => { :field => @customerrelations }
        .row
          .col-xs-12
            .f
              = render :partial => 'canvasfield', :locals => { :field => @channels }
      .col-md-2.nopadding
        .f2
          = render :partial => 'canvasfield', :locals => { :field => @customersegments }

    .row.bottom
      .col-md-6.nopadding
        .f
          = render :partial => 'canvasfield', :locals => { :field => @coststructure }
      .col-md-6.nopadding
        .f
          = render :partial => 'canvasfield', :locals => { :field => @revenuestreams }

  .col-md-3
    = render :partial => 'shared/username'
    .panel.panel-default
      .panel-heading
        = link_to "Comments", '#comments_Businessmodel', data: { toggle: "modal" }
        .pull-right
          = link_to '+', '#new_comment', data: { toggle: "modal" }, :title => "New", :class => "badge"
      .panel-body
        = render @businessmodel.comments.limit(3)
        - if @businessmodel.comments.count > 3
          = link_to "(" + (@businessmodel.comments.count - 3).to_s + " more...)", '#comments_Businessmodel', data: { toggle: "modal" }

= render 'comments/new'
= render :partial => 'comments/index', :locals => { :tagit => "Businessmodel", :comments => @comments}

app/views/canvas_fields/show.haml
- provide(:title, 'Businessmodel')
- currently_at 'Businessmodel'
.row.top
  .pull-left
    %strong= link_to 'Back to Businessmodel', @canvasfield.businessmodel
.row.top.bottom
  .col-md-9.nopadding
    .f2
      .panel.panel-default
        .panel-heading
          = @canvasfield.title
          .pull-right
            = link_to '+', '#new_postit'+@canvasfield.id.to_s, data: { toggle: "modal" }, :title => "New", :class => "badge"
            = render :partial => 'postits/new',  :locals => { :fieldid => @canvasfield.id }

        .panel-body
          .row
            - @canvasfield.postits.each do |p|
              .col-md-4
                .panel.panel-warning
                  .panel-heading
                    = link_to p.title, '#edit_postit' + p.id.to_s, data: { toggle: "modal" }
                    = render :partial => 'postits/edit', :locals => { :postit => p}
                    - if p.link
                      - if p.link.size > 0
                        .pull-right
                          = link_to '', url_for(p.link), :target => "_blank", :class => "glyphicon glyphicon-link"
                  .panel-body
                    = p.content
  .col-md-3
    = render :partial => 'shared/username'
    .panel.panel-default
      .panel-heading
        = link_to "Comments", '#comments_' + @canvasfield.title.delete(' '), data: { toggle: "modal" }
        .pull-right
          = link_to '+', '#new_comment', data: { toggle: "modal" }, :title => "New", :class => "badge"
      .panel-body
        = render @canvasfield.comments.limit(3)
        - if @canvasfield.comments.count > 3
          = link_to "(" + (@canvasfield.comments.count - 3).to_s + " more...)", '#comments_' + @canvasfield.title.delete(' '), data: { toggle: "modal" }

= render 'comments/new'
= render :partial => 'comments/index', :locals => { :tagit => @canvasfield.title.delete(' '), :comments => @comments}

app/views/comments/_comment.haml
.panel.panel-info
  .panel-heading
    %small
      %strong= comment.username
      (
      = time_ago_in_words(comment.created_at)
      ago)
  .panel-body
    = comment.comment

app/views/comments/_index.haml
.modal.fade{:id => "comments_"+tagit, :tabindex => "-1"}
  .modal-header
    %h4.modal-title Comments
    = tagit
  .modal-body
    .modal-body-content
      = render comments
  .modal-footer
    %button.btn{"data-dismiss" => "modal", :type => "button"} Close

app/views/comments/_new.haml
#new_comment.modal.fade{:tabindex => "-1"}
  .modal-header
    %h4.modal-title New comment
  .modal-body
    .modal-body-content
      = form_for(@comment) do |f|
        .field
          = f.label :username
          = f.text_field(:username, :value => @username, :size => '10')
        .field
          = f.label :comment
          = f.text_area(:comment, :size => '30x10')
        .field
          = f.hidden_field :commentable_id, :value =>  @cid
          = f.hidden_field :commentable_type, :value => @type
          = f.submit "Save changes", class: "btn btn-large btn-primary"
          %button.btn{"data-dismiss" => "modal", :type => "button"} Close

app/views/layouts/_footer.haml
.nav.navbar-inverse{:role => "navigation"}
  .container-fluid
    .navbar-footer
      %ul.nav.navbar.navbar-nav
        %li
          = link_to "Help", help_path
        %li
          = link_to "About", about_path

app/views/layouts/_header.haml
.nav.navbar-inverse{:role => "navigation"}
  .container-fluid
    .navbar-header
      %button(type="button" class = "navbar-toggle" data-toggle="collapse" data-target = "#canvas-nav")
        %span.sr-only
          Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to( "Canvas Collaborator", root_url , :class => "brand", :id => "logo")

    .collapse.navbar-collapse#canvas-nav
      %ul.nav.navbar-nav.navbar-right
        = yield :main_navigation

app/views/layouts/_modal.haml
#ajax-modal.modal.hide.fade{:tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
    %h3.modal-title Campustask
  .modal-body
    .modal-body-content
    .ajax-loader
  .modal-footer
    %button.btn{"data-dismiss" => "modal", :type => "button"} Close

app/views/layouts/_nav.haml
- content_for :main_navigation do
  -# START_HIGHLIGHT
  = nav_tab 'Home', root_path, current: current_tab
  - if current_model?
    = nav_tab 'Businessmodel', @businessmodel, current: current_tab
    -# END_HIGHLIGHT

app/views/layouts/application.haml
!!!
%html

  %head
    %meta{:charset => "utf-8"}/
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    - if debug_enabled?
      = stylesheet_link_tag("debug")
    = csrf_meta_tags
    /[if lt IE 9]
      %script{ src: "http://html5shim.googlecode.com/svn/trunk/html5.js"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/

  %body
    = render 'layouts/header'

    .container
      = yield :sub_navigation
      %section#content
        - flash.each do |key, value|
          = content_tag(:div, value, class: "alert alert-#{key}")
        = yield

    = render 'layouts/footer'

app/views/postits/_edit.haml
.modal.fade{:id => "edit_postit#{postit.id}", :tabindex => "-1"}
  .modal-header
    %h4 Edit postit
  .modal-body
    .modal-body-content
      = form_for(postit) do |f|
        .row
          .col-md-3
            = f.label :title
          .col-md-6
            = f.text_field(:title, :size => 40)
        .row
          .col-md-3
            = f.label :content
          .col-md-6
            = f.text_area(:content, :size => '40x5')
        .row
          .col-md-3
            = f.label :link
          .col-md-6
            = f.text_field(:link, :size => 40)
        .row.pull-right
          %button.btn{"data-dismiss" => "modal", :type => "button"} Close
          = f.submit "Save changes", class: "btn btn-large btn-primary"

app/views/postits/_new.haml
.modal.fade{:id=> "new_postit#{fieldid}", :tabindex => "-1"}
  .modal-header
    %h4.modal-title New postit
  .modal-body
    .modal-body-content
      = form_for(@postit) do |f|
        .row
          .col-md-3
            = f.label :title
          .col-md-6
            = f.text_field(:title, :size => 40)
        .row
          .col-md-3
            = f.label :content
          .col-md-6
            = f.text_area(:content, :size => '40x5')
        .row
          .col-md-3
            = f.label :link
          .col-md-6
            = f.text_field(:link, :size => 40)
        .row.pull-right
          = f.hidden_field :canvas_field_id, :value =>  fieldid
          %button.btn{"data-dismiss" => "modal", :type => "button"} Close
          = f.submit "Save changes", class: "btn btn-large btn-primary"

app/views/postits/_postit.haml
.panel.panel-warning.postit
  .panel-heading
    = link_to postit.title, '#edit_postit' + postit.id.to_s, data: { toggle: "modal" }
    - if postit.link
      - if postit.link.size > 0
        .pull-right
          = link_to '', url_for(postit.link), :target => "_blank", :class => "glyphicon glyphicon-link"
= render :partial => 'postits/edit', :locals => { :postit => postit}

app/views/postits/edit.haml
%h4 Edit postit
= form_for(@postit) do |f|
  .field
    = f.label :title
  .field
    = f.text_field(:title, :size => 40)
  .field
    = f.label :content
  .field
    = f.text_area(:content, :size => '30x10')
  .field
    = f.submit "Save changes", class: "btn btn-large btn-primary"

app/views/postits/new.haml
.row
  .col-md-8
    %h4 Neuer Eintrag
    = form_for(@postit) do |f|
      .field
        = f.label :title
        = f.text_field(:title, :size => 40)
      .field
        = f.label :content
        = f.text_area(:content, :size => '30x10')
      .field
        = f.hidden_field :canvas_field_id, :value =>  @canvasfield.id
        = f.submit "Save changes", class: "btn btn-large btn-primary"

app/views/shared/_username.haml
.panel.panel-default
  .panel-body
    = form_for :businessmodel, :url => url_for(:controller => 'businessmodels', :action => 'user') do |f|
      .field
        = f.text_field(:username, :value => @username, :size => 20)
        = f.submit(:value => "ok", :class => "btn btn-xs")

app/views/static_pages/about.haml
- provide(:title, 'About')
- currently_at 'About'

.row
.col-md-3
.col-md-6
  .startpage

    %h3 Canvas Collaborator
    .top
      This is a simple application that helps you to create and discuss your business
      model with your team, using the 'business model canvas' known from the book
      'business model generation'.

    %h3 Nils Löwe
    .top.bottom
      Über Nils

.col-md-3

app/views/static_pages/help.haml
- provide(:title, 'Help')
- currently_at 'Help'

.row
.col-md-3
.col-md-6
  .startpage

    %h3 What is the canvas?
    .top
      The introduction to the businessmodel canvas


    %h3 How do I use the tool?
    .top.bottom
      Introduction to the tool

.col-md-3

app/views/static_pages/home.haml
- provide(:title, 'Home')
- currently_at 'Home'

.row
.col-md-3
.col-md-6
  .startpage
    %h3 Welcome to the Canvas Collaborator

    .top
      This is a simple application that helps you to create and discuss your business
      model with your team, using the 'business model canvas' known from the book
      'business model generation'.

    .top
      The tool is completely free and open source, so just start testing or using it:

    .top.bottom
      = link_to('Create Canvas', new_businessmodel_path, :class => "btn btn-large btn-primary")

.col-md-3